### ISSUE TITLE
Add missing Entity Type definitions (supported by Amundsen)

### ISSUE THREAD

**Issue by verdan** [ing-bank/rokku-dev-apache-atlas#18]

**Comment by kr7ysztof** [comment]
I do not know the type definitions so please create PR and add the types you want here: [typedef-ingestion-source.json](https://github.com/ing-bank/rokku-dev-apache-atlas/blob/master/model/typedef-ingestion-source.json) and the rest will be done during atlas init by [atlas-setup.sh](https://github.com/ing-bank/rokku-dev-apache-atlas/blob/master/resources/atlas-setup.sh)

**Comment by verdan** [comment]
Fixed after merging this one: https://github.com/ing-bank/rokku-dev-apache-atlas/pull/20
