### ISSUE TITLE
[Question] Which directory mounts do I need for persistence

### ISSUE THREAD

**Issue by dcrdev** [ing-bank/rokku-dev-apache-atlas#21]
Trying to utilise this as part of an existing deployment we have and am trying to make the data persistent, I'm not entirely clear on which directory mounts I need to make.

So far I've got a horrible workaround - which I'd try and like to avoid.

I've tried:
 ```
/opt/atlas/data
```

But doesn't look like solr comes back online afterwards.

**Comment by kr7ysztof** [comment]
The docker dev atlas version is based on `embedded-hbase-solr` https://github.com/ing-bank/rokku-dev-apache-atlas/blob/master/Dockerfile#L11, so you need to pesist data from hbase, solar, zookeeper.
Maybe it is better for you to prepare docker atlas with external storage or you need to analyze the start script https://github.com/ing-bank/rokku-dev-apache-atlas/blob/master/resources/entrypoint.sh#L7 what are the exect paths the data are kept :)
For us it is enough to have an init script https://github.com/ing-bank/rokku-dev-apache-atlas/blob/master/resources/atlas-setup.sh where you can put types and data you always need.
